# Generated by Django 6.0.4 on 2026-04-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='tax_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
