# Generated by Django 6.0.4 on 2026-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='province',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
