# Generated by Django 6.0.4 on 2026-05-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_update_addresses_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyaddress',
            old_name='employer',
            new_name='employer_profile',
        ),
        migrations.RenameField(
            model_name='companyverificationimage',
            old_name='employer',
            new_name='employer_profile',
        ),
    ]
