# Generated by Django 6.0.4 on 2026-05-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_employer_companyaddress_employer_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
