# Generated by Django 6.0.4 on 2026-05-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_companyaddress_uuid_companyverificationimage_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='full_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
