# Generated by Django 6.0.4 on 2026-05-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_companyaddress_full_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='full_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
