# Generated by Django 6.0.4 on 2026-05-20 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_companyaddress_full_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyverificationimage',
            name='employer_profile',
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=20)),
                ('employer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='accounts.employerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='companyverificationimage',
            name='verification_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.verificationrequest'),
            preserve_default=False,
        ),
    ]
