# Generated by Django 6.0.4 on 2026-05-21 02:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_companyverificationimage_employer_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
