# Generated by Django 6.0.4 on 2026-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_verificationrequest_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='full_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
