# Generated by Django 6.0.4 on 2026-05-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_jobapplication_message_alter_jobapplication_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='candidate',
            new_name='candidate_profile',
        ),
    ]
