# Generated by Django 6.0.4 on 2026-05-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_rename_candidate_resume_candidate_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
