# Generated by Django 6.0.4 on 2026-05-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='employer',
            new_name='employer_profile',
        ),
    ]
