# Generated by Django 6.0.4 on 2026-05-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_employer_jobpost_employer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
