# Generated by Django 6.0.4 on 2026-05-20 10:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_companyaddress_full_address'),
        ('applications', '0006_alter_resume_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('review', models.TextField()),
                ('recommendation_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_comments', to='accounts.candidateprofile')),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_comment', to='applications.jobapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('review', models.TextField()),
                ('recommendation_rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_comments', to='accounts.employerprofile')),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_comment', to='applications.jobapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.employerprofile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='accounts.candidateprofile')),
            ],
            options={
                'unique_together': {('follower', 'followed')},
            },
        ),
    ]
